networks:
  feecheckr:
    driver: bridge

services:
  # fee-giver:
  #   container_name: FeeGiver
  #   build: "./FeeGiver"
  #   ports:
  #     - 5174:5174
  #   networks:
  #     - feecheckr
  #   volumes:
  #     - ./FeeGiver:/app
  #   depends_on:
  #     - fee-checkrer

  # fee-checkr:
  #   container_name: FeeCheckr 
  #   build: "./FeeCheckr"
  #   ports:
  #     - 5173:5173
  #   environment:
  #     - VITE_APP_SERVER_URL=http://FeeCheckrer:3000/
  #     - SERVER_URL=http://FeeCheckrer:3000/
  #   networks:
  #     - feecheckr
  #   volumes:
  #     - ./FeeCheckr:/app
  #   depends_on:
  #     - fee-checkrer

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - feecheckr

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - feecheckr
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  fee-checkrer:
    build: "./FeeCheckrer"
    container_name: server
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://root:password@mongodb:27017/dev?authSource=admin
      JWT_SECRET: "astaghfirullah"
      JWT_TEMP_SECRET: "astaghfirullah2"
      PORT: 3000
    networks:
      - feecheckr
    volumes:
      - ./FeeCheckrer:/app
    depends_on:
      - mongodb

volumes:
  mongo-data:
    driver: local
