networks:
  feecheckr:
    driver: bridge

services:
  # fee-giver:
  #   container_name: FeeGiver
  #   build: "./FeeGiver"
  #   ports:
  #     - 5174:5174
  #   networks:
  #     - feecheckr
  #   env_file: "./FeeGiver/.env"
  #   volumes:
  #     - ./FeeGiver:/app
  #   depends_on:
  #     - fee-checkrer

  # fee-checkr:
  #   container_name: FeeCheckr 
  #   build: "./FeeCheckr"
  #   ports:
  #     - 5173:5173
  #   env_file: "./FeeCheckr/.env"
  #   networks:
  #     - feecheckr
  #   volumes:
  #     - ./FeeCheckr:/app
  #   depends_on:
  #     - fee-checkrer

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - feecheckr

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - feecheckr
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  fee-checkrer:
    build: "./FeeCheckrer"
    container_name: server
    ports:
      - "3000:3000"
    environment:
      AMQP_URI: amqp://rabbit:QAmTZ0LufU@rabbitmq

      REDIS_HOST: redis
      REDIS_PORT: 6379

      MONGO_URI: mongodb://root:password@mongodb:27017/dev?authSource=admin
      JWT_SECRET: "astaghfirullah"
      JWT_TEMP_SECRET: "astaghfirullah2"
      PORT: 3000

      FIREBASE_API_KEY: AIzaSyATBThrcStzkwVCTu_js9tfDI-QtEcZA4A
      FIREBASE_AUTH_DOMAIN: genz-feats.firebaseapp.com
      FIREBASE_DB_URL: https://genz-feats-default-rtdb.asia-southeast1.firebasedatabase.app
      FIREBASE_PROJECT_ID: genz-feats
      FIREBASE_STORAGE_BUCKET: genz-feats.appspot.com
      FIREBASE_MESSAGING_SENDER_ID: 258868436534
      FIREBASE_APP_ID: 1:258868436534:web:42d47c92d2cab9730e0297
      FIREBASE_MEASUREMENT_ID: G-HR6B46QBCF

    networks:
      - feecheckr
    volumes:
      - ./FeeCheckrer:/app
    depends_on:
      - mongodb

  rabbitmq:
    image: rabbitmq:4-alpine
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment: 
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: QAmTZ0LufU 
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - feecheckr

  mailer:
    build: "./mailer"
    container_name: mailer
    ports: 
      - "6546:6546"
    environment:
      GMAIL_ADDR: ainsa2279@gmail.com
      GMAIL_PASS: iqmeutnalmajjkvz
      AMQP_URI: amqp://rabbit:QAmTZ0LufU@rabbitmq
    volumes:
      - ./mailer:/app
    depends_on:
      - rabbitmq
    networks:
      - feecheckr

volumes:
  mongo-data:
    driver: local
  rabbitmq-data: 
    driver: local
